[2023-06-22T06:42:16.104+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: time_task.create_table manual__2023-06-22T06:42:14.866751+00:00 [queued]>
[2023-06-22T06:42:16.154+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: time_task.create_table manual__2023-06-22T06:42:14.866751+00:00 [queued]>
[2023-06-22T06:42:16.158+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-22T06:42:16.316+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-06-22 06:42:14.866751+00:00
[2023-06-22T06:42:16.330+0000] {standard_task_runner.py:57} INFO - Started process 71 to run task
[2023-06-22T06:42:16.342+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'time_task', 'create_table', 'manual__2023-06-22T06:42:14.866751+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/create_postgres_table.py', '--cfg-path', '/tmp/tmpl7pz3v3g']
[2023-06-22T06:42:16.343+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask create_table
[2023-06-22T06:42:16.477+0000] {task_command.py:410} INFO - Running <TaskInstance: time_task.create_table manual__2023-06-22T06:42:14.866751+00:00 [running]> on host b9a60b2e230a
[2023-06-22T06:42:16.568+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='time_task' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-22T06:42:14.866751+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-22T06:42:14.866751+00:00'
[2023-06-22T06:42:16.570+0000] {sql.py:265} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS myTime (
                curr_time TIMESTAMP
            );
        
[2023-06-22T06:42:16.588+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-06-22T06:42:16.684+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-06-22T06:42:16.694+0000] {sql.py:375} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS myTime (
                curr_time TIMESTAMP
            );
        , parameters: None
[2023-06-22T06:42:16.700+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(mytime, 2200) already exists.

[2023-06-22T06:42:16.713+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=time_task, task_id=create_table, execution_date=20230622T064214, start_date=20230622T064216, end_date=20230622T064216
[2023-06-22T06:42:16.724+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 4 for task create_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(mytime, 2200) already exists.
; 71)
[2023-06-22T06:42:16.753+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-22T06:42:16.780+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
